Add backlog of changelogs from QMK Firmware
qmk/qmk.fm_old pull request #48
Opened 2019-04-25 04:32 UTC by drashna

2019-04-25 04:37 UTC, jackhumbert commented on _posts/2019-02-21-velocikey-match-rgb-animation-spped-to-typing-speed.md
> +title: "Velocikey: Match RGB animation speed to typing speed"
Might have a typo in the filename here :)

2019-04-25 05:05 UTC, noroadsleft requested changes

2019-04-25 05:05 UTC, noroadsleft commented on _posts/2019-02-25-added-boardwalk-keyboard.md
> +title: "{Keyboard] Add boardwalk Keyboard"
```suggestion
title: "[Keyboard] Add Boardwalk Keyboard"
```

2019-04-25 05:05 UTC, noroadsleft commented on _posts/2019-03-11-keyboard-add-hotdox-keyboard.md
> +You can also find the [Kono Store](https://kono.store/products/ergodox-hotdox).
```suggestion
You can also find the HotDox for sale on [Kono Store](https://kono.store/products/ergodox-hotdox).
```

2019-04-25 05:05 UTC, noroadsleft commented on _posts/2019-03-12-next-set-of-split-common-changes.md
> +THis updates a number of parts for the Split Keyboard code, to get it more ready for ARM Support (no, not here yet).
```suggestion
This updates a number of parts for the Split Keyboard code, to get it more ready for ARM Support (no, not here yet).
```

2019-04-25 05:05 UTC, noroadsleft commented on _posts/2019-03-12-next-set-of-split-common-changes.md
> +* Support greater than 8 columns for i2c based split keyboards
```suggestion
* Support greater than 8 columns for i2c-based split keyboards
```

2019-04-25 05:05 UTC, noroadsleft commented on _posts/2019-03-13-add-support-for-the60.md
> +Check out this keyboard on the [QMK Configurator](https://config.qmk.fm/#/hotdox/LAYOUT_ergodox).
Link address is wrong.

```suggestion
Check out this keyboard on the [QMK Configurator](https://config.qmk.fm/#/lazydesigners/the60/LAYOUT_split_spc_split_bspc).
```

2019-04-25 05:05 UTC, noroadsleft commented on _posts/2019-03-26-add-3-speed-mousekey-movement-options.md
> +This allows for a constant movement speed with Mousekeys may allow for more precise movement.
```suggestion
This allows for a constant movement speed with Mousekeys which may allow for more precise movement.
```

2019-04-25 05:05 UTC, noroadsleft commented on _posts/2019-04-11-port-direct-pins-from-split-common-matrix-to-matrix-c.md
> +Adds support for Direct Pin connection keyboards (eg, no matrix, no diodes, just connected to the controller)
Grammar fixes.

```suggestion
Adds support for Direct Pin connection keyboards (e.g. no matrix, no diodes, just connected to the controller).
```

2019-04-25 05:05 UTC, noroadsleft commented on _posts/2019-04-12-add-altgr-ralt-support-to-send-string.md
> +Adds support for AltGR, allowing for non-US keycodes in `SEND_STRING`
Missing a period.

```suggestion
Adds support for AltGR, allowing for non-US keycodes in `SEND_STRING`.
```

2019-04-25 05:05 UTC, noroadsleft commented on _posts/2019-04-19-oled-driver-feature.md
> +This driver is smaller and faster, and includes features such as rotation of the OLED, or scroll an image
Grammar/readability.

```suggestion
This driver is smaller and faster, and includes features such as rotation of the OLED, or scrolling an image.
```

2019-05-12 06:56 UTC, noroadsleft approved these changes
Looks good to me. :+1:

2019-05-14 02:52 UTC, drashna commented
@jackhumbert ?

2019-05-14 04:07 UTC, merged

2019-05-14 04:07 UTC, jackhumbert commented
Thanks :)