[Vitamins Included] Added found design flaws in rev 2.0
qmk/qmk.fm_old pull request #55
Opened 2019-08-23 01:46 UTC by Duckle29

Two design flaws have been found and I detailed them in the documentation for it.

2019-09-29 22:00 UTC, Duckle29 commented
I also added some updated 3D models. Printed and confirmed fitting.

2019-10-25 22:39 UTC, drashna commented
Merge conflict :(

2019-10-29 09:45 UTC, Duckle29 commented
well that didn't work... wat

2019-10-29 10:19 UTC, Duckle29 commented
The merge conflict was due to the _pages being moved. it has been solved :)

2020-02-06 04:32 UTC, drashna approved these changes

2020-02-06 04:43 UTC, fauxpark requested changes

2020-02-06 04:43 UTC, fauxpark commented on _i18n/en/keyboards/vitamins_included.md
> +## NOTE: Rev 2.0 has an error in the labeling of the LED_O jumpers on the right half. They are swapped. Just the lables are swapped. Functionally they're identical.
```suggestion
#### NOTE: Rev 2.0 has an error in the labeling of the `LED_O` jumpers on the right half. The labels are swapped, but are functionally identical to the previous revision.
```

2020-02-06 04:51 UTC, fauxpark approved these changes

2020-02-06 04:52 UTC, merged