French translation
qmk/qmk.fm_old pull request #66
Opened 2019-10-08 21:29 UTC by MattMattV

Here is my modest contribution to the QMK software, a french translation of the website ! :tada: 

I felt free to manipulate a bit some sentences to be more "french friendly" more than translate word by word.

Also it has a great chance that typos invited to the party, even if I re-re-read my text :eyes:

2019-10-23 08:25 UTC, Darkpingouin commented
Hey, I am reviewing your files and there are some typos, not too much so I won't open a pull request for them as it would not be usefull.
- File ` _i18n/fr/coc.md ` line **14** you typed `régir` instead of `réagir`
- File `_i18n/fr/sidebar.md` line **1** you type `n'import` instead of  `n'importe`

2019-10-23 08:27 UTC, Darkpingouin commented
Fixes https://github.com/qmk/qmk_firmware/issues/6924
I would also Add the labels hactkoberfest and translation to your PR

2019-10-23 18:20 UTC, noroadsleft commented
@zekth Would you mind reviewing this translation please?

2019-10-23 18:29 UTC, zekth requested changes
Minor fix. Otherwise ok to me

2019-10-23 18:29 UTC, zekth commented on _i18n/fr/coc.md
> +QMK s'efforce d'être une communauté, accueillante, tolérante et inclusive. Nous encourageons toutes les contributions indépendamment de l'âge, de quelconque handicap, de l'appartenance éthnique, du g
```suggestion
QMK s'éfforce d'être une communauté, accueillante, tolérante et inclusive. Nous encourageons toutes les contributions indépendamment de l'âge, de quelconque handicap, de l'appartenance ethnique, du genre, du niveau d'expérience technique, de la nationalité, de l'apparence physique, des orientations politiques, de la race, de la religion ou de l'orientation et de l'identification sexuelle.
```

2019-10-23 18:29 UTC, zekth commented on _i18n/fr/coc.md
> +Nous attendons de nos utilisateurs, contributeurs et collaborateurs qu'ils se traitent avec gentillesse et respect, qu'ils aient de bonnes intentions, de corriger avec pédagogie, quand cela est possi
```suggestion
Nous attendons de nos utilisateurs, contributeurs et collaborateurs qu'ils se traitent avec gentillesse et respect, qu'ils aient de bonnes intentions, de corriger avec pédagogie, quand cela est possible, plutôt que de réagir de façon disproportionnée. Même si notre but est d'être aussi précis que possible, la compréhension et la gentillesse sont plus précieuses que l'exactitude.
```

2019-10-23 18:29 UTC, zekth commented on _i18n/fr/sidebar.md
> +Le but du projet QMK est de développer un firmware complètement personnalisable, puissant et facile à utiliser pour tous type de projet de clavier ou autre, et de fournir une aide bienveillante, enco
```suggestion
Le but du projet QMK est de développer un firmware complètement personnalisable, puissant et facile à utiliser pour tous type de projet de clavier ou autre, et de fournir une aide bienveillante, encourageante et utile ainsi que des retours pour des personnes avec n'importe quelle expérience en développement logiciel.
```

2019-10-26 21:24 UTC, Ph0tonic commented on _i18n/fr/coc.md
> +Si quelqu'un viole ce Code de Conduite, veuillez envoyer un email à hello arobase qmk.fm ou contactez l'un des collaborateur. Toutes les plaintes seront évaluées et prises en considération.
Si quelqu'un viole ce Code de Conduite, veuillez envoyer un email à hello@qmk.fm ou contactez l'un des collaborateur. Toutes les plaintes seront évaluées et prises en considération.

2019-10-26 21:24 UTC, Ph0tonic commented on _i18n/fr/coc.md
> +Si quelqu'un viole ce Code de Conduite, veuillez envoyer un email à hello arobase qmk.fm ou contactez l'un des collaborateur. Toutes les plaintes seront évaluées et prises en considération.
Missing a real arobase.

2019-10-26 21:25 UTC, Ph0tonic requested changes
Small details

2019-10-26 21:28 UTC, Ph0tonic commented on _i18n/fr/support.md
> +* Envoyer des goodies à des meetups pour offrir ou pour des concours. Envoyez nous un email si vous êtes intéressés ! hello arobase qmk.fm
Missing a real arobase:
`* Envoyer des goodies à des meetups pour offrir ou pour des concours. Envoyez nous un email si vous êtes intéressés ! hello@qmk.fm`

2019-10-28 19:22 UTC, noroadsleft requested changes
Changes as requested by @Ph0tonic

2019-10-28 19:22 UTC, noroadsleft commented on _i18n/fr/coc.md
> +Si quelqu'un viole ce Code de Conduite, veuillez envoyer un email à hello arobase qmk.fm ou contactez l'un des collaborateur. Toutes les plaintes seront évaluées et prises en considération.
```suggestion
Si quelqu'un viole ce Code de Conduite, veuillez envoyer un email à hello@qmk.fm ou contactez l'un des collaborateur. Toutes les plaintes seront évaluées et prises en considération.
```

2019-10-28 19:22 UTC, noroadsleft commented on _i18n/fr/support.md
> +* Envoyer des goodies à des meetups pour offrir ou pour des concours. Envoyez nous un email si vous êtes intéressés ! hello arobase qmk.fm
```suggestion
* Envoyer des goodies à des meetups pour offrir ou pour des concours. Envoyez nous un email si vous êtes intéressés ! hello@qmk.fm
```

2019-10-29 08:27 UTC, Ph0tonic approved these changes

2019-10-29 21:11 UTC, noroadsleft commented
Going to merge this as-is and then do another PR that integrates suggestions from @Darkpingouin, @zekth and @Ph0tonic.

I don't like writing to other user's branches without their explicit permission, and I'd like to get this across the line.

Thank you all for your contributions!

2019-10-29 21:13 UTC, noroadsleft approved these changes

2019-10-29 21:13 UTC, merged