Add Spanish translations
qmk/qmk.fm_old pull request #67
Opened 2019-10-09 15:26 UTC by kbravh

I've added a Spanish translation for almost all files except the keyboards.md. 

I also added a translation for the license.md file. The translations are not official translations of the licenses, but may serve to let Spanish speakers better understand what the licenses consist of.

I added a disclaimer at the top of the page saying they aren't official translations and advise the user to refer to the official licenses in English with a link to the English license page.

Is this the route we want to take for the licenses? I can remove the translation altogether to fallback to the English license page.

2019-10-26 06:16 UTC, kuchosauronad0 commented on _i18n/es/changes.md
> +{% for change in site.changes %}
```suggestion
{% for change in site.changes reversed %}
```
This way the most recent change is at the top of the page. See #78

2019-10-28 19:44 UTC, noroadsleft commented
Merged updated branch to fix a merge conflict (lol).

@namelivia do you mind reviewing this for me?

2019-10-31 08:53 UTC, noroadsleft requested changes

2019-10-31 08:53 UTC, noroadsleft commented on _i18n/es/coc.md
> +lang: "es"
```suggestion
permalink: /es/coc/
lang: "es"
```

2019-10-31 08:53 UTC, noroadsleft commented on _i18n/es/converter.md
> +lang: "es"
```suggestion
permalink: /es/converter/
lang: "es"
```

2019-10-31 08:53 UTC, noroadsleft commented on _i18n/es/flasher.md
> +lang: "es"
```suggestion
permalink: /es/flasher/
lang: "es"
```

... Though I'm not actually sure this page is used anymore.

2019-10-31 08:53 UTC, noroadsleft commented on _i18n/es/license.md
> +lang: "es"
```suggestion
permalink: /es/license/
lang: "es"
```

2019-10-31 08:53 UTC, noroadsleft commented on _i18n/es/powered.md
> +lang: "es"
```suggestion
permalink: /es/powered/
lang: "es"
```

2019-10-31 08:53 UTC, noroadsleft commented on _i18n/es/proton-c.md
> +lang: "es"
```suggestion
permalink: /es/proton-c/
lang: "es"
```

2019-10-31 08:53 UTC, noroadsleft commented on _i18n/es/support.md
> +lang: "es"
```suggestion
permalink: /es/support/
lang: "es"
```

2019-10-31 08:53 UTC, noroadsleft commented on _i18n/es/toolbox.md
> +lang: "es"
```suggestion
permalink: /es/toolbox/
lang: "es"
```

2019-10-31 08:58 UTC, namelivia commented
@noroadsleft Could you create a review request for me user so I don't forget about this? Thanks

2019-10-31 09:07 UTC, noroadsleft commented
@namelivia I actually can't; GitHub won't let me review request anyone who isn't a Member of QMK. I'm not sure if this is a GitHub limitation, or a limitation because the repository is owned by an organization rather than a user. (I've wanted to do this on other QMK repos too, and I can't do it there either.)

If you can't get to it, it's okay. Anything broken or wrong can be fixed later.

2019-11-01 00:34 UTC, kbravh commented
Alright, I've added the permalinks!

2019-11-01 00:45 UTC, noroadsleft approved these changes
Looks good, thanks!

2019-11-01 00:46 UTC, merged