Fix broken gitbook link in the front page
qmk/qmk.fm_old pull request #72
Opened 2019-10-21 19:57 UTC by cyky

- Gitbook link pointed into 404 page. Fixed the link based on the link used in German translation.

Should fix the link issue mentioned in https://github.com/qmk/qmk_firmware/issues/7054

2019-10-24 14:35 UTC, sagarvd01 approved these changes
The domain https://qmk-1.gitbook.io is invalid. Valid one is https://qmk.gitbook.io, which redirects to the https://docs.qmk.fm/#/

2019-10-27 23:34 UTC, fauxpark requested changes

2019-10-27 23:34 UTC, fauxpark commented on _i18n/en/index.md
> +[Documentation](https://docs.qmk.fm) is hosted on [Gitbook](https://docs.qmk.fm) and [Github](https://github.com/qmk/qmk_firmware/tree/master/docs) (they are synced). You can request changes by makin
```suggestion
[The official documentation](https://docs.qmk.fm) is powered by [Docsify](https://docsify.js.org/) and hosted on [GitHub](https://github.com/qmk/qmk_firmware/tree/master/docs). You can request changes by making a fork and [pull request](https://github.com/qmk/qmk_firmware/pulls) or by clicking the "Edit Document" link at the bottom of any page.
```

We don't use Gitbook anymore - this suggestion brings the text more in line with what's currently in the qmk_firmware readme.

2019-10-28 19:55 UTC, cyky commented
Translated versions will need the same change.

2019-10-28 20:02 UTC, noroadsleft commented
> Translated versions will need the same change.

I plan on doing this after getting a number of these translations in, and then updating them all in one go.

2019-10-28 20:03 UTC, noroadsleft approved these changes
Looks good!

2019-10-28 21:46 UTC, fauxpark approved these changes

2019-10-28 21:47 UTC, merged