Add Hindi Translation for main page
qmk/qmk.fm_old pull request #76
Opened 2019-10-25 21:23 UTC by MetalDent

Translated few pages into Hindi.

Hope the format and spellings are correct.

2019-10-28 17:27 UTC, parammittal16 commented on _data/strings.yml
> +
I think space is necessary here?

2019-10-28 17:28 UTC, parammittal16 reviewed
LGTM :) Only that space one issue.

2019-10-31 09:03 UTC, noroadsleft requested changes

2019-10-31 09:03 UTC, noroadsleft commented on _data/strings.yml
> +    qmk_firmware: "QMK-फर्मवेयर"
Key-value pairs for `made_possible`, `hosted_on`, and `description` are also needed here.

See below for the English text.

https://github.com/qmk/qmk.fm/blob/27bc9ef1e3de79a21d387d4298201fb985dc3b4f/_data/strings.yml#L2-L8

2019-10-31 09:03 UTC, noroadsleft commented on _i18n/hi/changes.md
> +---
```suggestion
lang: "hi"
---
```

2019-10-31 09:03 UTC, noroadsleft commented on _i18n/hi/changes.md
> +{% for change in site.changes %}
A recent change to upstream.

```suggestion
{% for change in site.changes reversed %}
```

2019-11-01 04:16 UTC, noroadsleft commented on _i18n/hi/sidebar.md
> +* [QMK में हाल के बदलाव](/changes/)
```suggestion
* [QMK में हाल के बदलाव](/hi/changes/)
```

2019-11-01 04:17 UTC, noroadsleft commented
Thanks!

2019-11-01 04:17 UTC, merged